import cv2

from wham.models.wham_token_model.wham_token import WHAMTokenModule

# Hardcoded number (the FPS model was trained for)
DREAMING_FPS = 10

# Watermark configs
WATERMARK_TEXT = "Generated by WHAM"
PROGRAM_NAME = "Generated by WHAM (World Human-Action Model)"
WATERMARK_FONT = cv2.FONT_HERSHEY_SIMPLEX
WATERMARK_FONT_COLOR = (255, 255, 255)
WATERMARK_FONT_SCALE = 0.4
WATERMARK_FONT_THICKNESS = 1

POS_BINS_BOUNDARIES = [-1.05, -0.95, -0.75, -0.5, -0.25, -0.05, 0.05, 0.25, 0.5, 0.75, 0.95, 1.05]

POS_BINS_MIDDLE = [-1, -0.85, -0.625, -0.375, -0.15, 0, 0.15, 0.375, 0.625, 0.85, 1]

def load_model_from_checkpoint(load_checkpoint_path):
    # Need to do this trickery as we changed names of the module
    import wham
    import sys
    sys.modules["humanmodelling"] = wham
    return WHAMTokenModule.load_from_checkpoint(load_checkpoint_path, strict=False, map_location="cpu")